// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	models "github.com/desulaidovich/auth/auth/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: guid, token
func (_m *Repository) Add(guid string, token string) (*models.Token, error) {
	ret := _m.Called(guid, token)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.Token, error)); ok {
		return rf(guid, token)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.Token); ok {
		r0 = rf(guid, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(guid, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: guid
func (_m *Repository) Get(guid string) (*models.Token, error) {
	ret := _m.Called(guid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Token, error)); ok {
		return rf(guid)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Token); ok {
		r0 = rf(guid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
